#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : d9vk
Version  : 0.30
Release  : 1
URL      : https://github.com/Joshua-Ashton/d9vk/archive/0.30.tar.gz
Source0  : https://github.com/Joshua-Ashton/d9vk/archive/0.30.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause Zlib
Requires: d9vk-lib = %{version}-%{release}
Requires: d9vk-license = %{version}-%{release}
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Loader-dev32
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glslang
BuildRequires : mingw-binutils
BuildRequires : pkgconfig(32vulkan)
BuildRequires : pkgconfig(vulkan)
BuildRequires : util-linux
BuildRequires : wine
BuildRequires : wine-dev
BuildRequires : wine-dev32
BuildRequires : wine-extras-staticdev

%description
# DXVK
A Vulkan-based translation layer for Direct3D 10/11 which allows running 3D applications on Linux using Wine.

%package lib
Summary: lib components for the d9vk package.
Group: Libraries
Requires: d9vk-license = %{version}-%{release}

%description lib
lib components for the d9vk package.


%package lib32
Summary: lib32 components for the d9vk package.
Group: Default
Requires: d9vk-license = %{version}-%{release}

%description lib32
lib32 components for the d9vk package.


%package license
Summary: license components for the d9vk package.
Group: Default

%description license
license components for the d9vk package.


%prep
%setup -q -n d9vk-0.30
cd %{_builddir}/d9vk-0.30

%build
## build_prepend content
meson --cross-file build-wine64.txt --buildtype release --prefix `pwd -P`/64 build.w64
pushd build.w64
ninja
popd
meson --cross-file build-wine32.txt --buildtype release --prefix `pwd -P`/32 build.w32
pushd build.w32
ninja
popd
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572471400
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  ||:


%install
export SOURCE_DATE_EPOCH=1572471400
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/d9vk
cp %{_builddir}/d9vk-0.30/LICENSE %{buildroot}/usr/share/package-licenses/d9vk/4a83b2fbabc7965ffeffdda9b49248867c18e621
cp %{_builddir}/d9vk-0.30/include/openvr/LICENSE %{buildroot}/usr/share/package-licenses/d9vk/99e40ce3676d57f631fca8692017203185ab6b5f
%make_install ||:
## install_append content
mkdir -p %{buildroot}/usr/lib64/wine
install build.w64/src/d3d9/d3d9.dll.so %{buildroot}/usr/lib64/wine/
mkdir -p %{buildroot}/usr/lib32/wine
install build.w32/src/d3d9/d3d9.dll.so %{buildroot}/usr/lib32/wine/
## install_append end

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/wine/d3d9.dll.so

%files lib32
%defattr(-,root,root,-)
/usr/lib32/wine/d3d9.dll.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/d9vk/4a83b2fbabc7965ffeffdda9b49248867c18e621
/usr/share/package-licenses/d9vk/99e40ce3676d57f631fca8692017203185ab6b5f
